### ISSUE TITLE
ArgumentException: Json field "id" with Value "att152011028" cannot be converted to Type System.Int64

### ISSUE THREAD

**Issue by RobVess** [dapplo/Dapplo.Confluence#18]
Hi, I have tried to work through this issue and have got stuck.

This code has been working for a long time (most of this year) but has just started failing.

I am trying to do the following
```
Query = Where.And(Where.Type.IsAttachment,
                              Where.Text.Contains("GLIFFY DIAGRAM"),
                              Where.Space.Is(pConfluence.ProjectSpaceKey),
                              Where.Label.Not().Is("obsolete"))
```
Then call 
`Results = Await pConfluence.Connection.Content.SearchAsync(Query, limit:=200)
`
This errors with 
ArgumentException: Json field "id" with Value "att152011028" cannot be converted to Type System.Int64

The stack trace is long but is all internal to Dapplo. It appears to be the PocoJSONSerializerStrategy taking the value "att152011028" which is the 3rd attachment ID according to https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-get-the-id-of-an-attachment/qaq-p/518429 this article. 

Looking at the dapplo.confluence.Entities.content.id field. This is an int64 as described in the exception.
This would seem to be the issue but I'm not sure why it has started happening unless Atlassian has changed the return values from their API or a mapping has gone wrong in the latest version released recently.

Any ideas greatly appreciated. 

Result StackTrace:	
Result StackTrace:	
```
at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.String.System.IConvertible.ToInt64(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 248
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 326
 --- End of inner exception stack trace ---
    at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 341
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 432
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 338
   at Dapplo.HttpExtensions.JsonSimple.SimpleJson.DeserializeObject(String json, Type type, IJsonSerializerStrategy jsonSerializerStrategy) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\SimpleJson.cs:line 169
   at Dapplo.HttpExtensions.JsonSimple.SimpleJsonSerializer.Deserialize(Type targetType, String jsonString) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\SimpleJsonSerializer.cs:line 71
   at Dapplo.HttpExtensions.ContentConverter.DefaultJsonHttpContentConverter.<ConvertFromHttpContentAsync>d__17.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\ContentConverter\DefaultJsonHttpContentConverter.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.HttpContentExtensions.<GetAsAsync>d__3.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpContentExtensions.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapplo.HttpExtensions.HttpResponseMessageExtensions.<GetAsAsync>d__1`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpResponseMessageExtensions.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.HttpClientExtensions.<GetAsAsync>d__4`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpClientExtensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.UriActionExtensions.<GetAsAsync>d__3`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\UriActionExtensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.Confluence.ContentExtensions.<SearchAsync>d__9.MoveNext() in C:\projects\dapplo-confluence\src\Dapplo.Confluence\ContentExtensions.cs:line 294
 --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Redgum.Tooling.Native.Expert_Threading.WaitSync[T](Task`1 pTask) in F:\RobsProfile\Documents\Visual Studio 2015\Projects\Redprint.Manager\Redgum.Tooling.Native\Expert_Threading.vb:line 48
   at Redprint.Studio.Confluence.Expert_Confluence.VB$StateMachine_32_Enumerate_Assets_InArchitectureDrawings.MoveNext() in F:\RobsProfile\Documents\Visual Studio 2015\Projects\Redprint.Manager\Redprint.Stuid.Confluence\Expert_Confluence.vb:line 384
   at Redprint.Manager.Confluence.Test.Test_GliffyDiagramParsing.Gliffy_Load_Assets_FromGliffy() in F:\RobsProfile\Documents\Visual Studio 2015\Projects\Redprint.Manager\Redprint.Manager.Confluence.Test\Test_GliffyDiagramParsing.vb:line 22
Result Message:	
Test method Redprint.Manager.Confluence.Test.Test_GliffyDiagramParsing.Gliffy_Load_Assets_FromGliffy threw exception: 
System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Json field "id" with Value "att152011028" cannot be converted to Type System.Int64 ---> System.FormatException: Input string was not in a correct format.

```

**Comment by Lakritzator** [comment]
I will need to check this, but I think I never thought about the use case, searching an attachment via the content domain. This was probably broken by ,the change on 22 Jun.

**Comment by RobVess** [comment]
Is there another way to get the body content of an attachment?

Also I revert to an older version and crashes at the same point with less detail about the error.

I know a Confluence update last week broke the Balsamiq

**Comment by Lakritzator** [comment]
I already have all the information to fix this, I just don't always have a lot of time while I have a kid (< 2 years), dog, wife and a normal full time job. 😄 

The problem here is plainly that the ID of an attachment is prefixed by "att" (for ATTatchment) and I expect content to have a numeric ID (since a more recent change). Don't know what Atlassian was thinking, but I already seen this a longer time ago. Why I didn't realize that there is a type conflict, I don't know either...

**Comment by Lakritzator** [comment]
Please try Dapplo.Confluence 0.7.1
Note:
There is no entity called Attachment anymore, everything is content.

An example is here:
https://github.com/dapplo/Dapplo.Confluence/blob/master/src/Dapplo.Confluence.Tests/ContentTests.cs#L134

Let me know if you have any issues.

**Comment by RobVess** [comment]
Thanks, I'm not sure I'm using it the right way but have solved it another way.
Your example test version gives me an empty string.

**Comment by Lakritzator** [comment]
Sorry, I somehow missed the email with the update from GitHub.
What other way did you use to solve it?

**Comment by RobVess** [comment]
ah, I went direct with the HttpExtensions library instead of the Confluence library. I just needed the raw text of the gliffy attachment

**Comment by Lakritzator** [comment]
Just closing this as I am sure my fix should work, and you have a different workaround.
So the issue doesn't make sense.

**Comment by RobVess** [comment]
Robin, yep close it, I have a working solution.
