### ISSUE TITLE
ArgumentException "Requested value 'personal' was not found." on search page 

### ISSUE THREAD

**Issue by KozhevnikovDmitry** [dapplo/Dapplo.Confluence#19]
Hello. I have a tricky issue on such code:

`
ConfluenceClient client = GetConfluenceClient();

var query = Where.And(Where.Type.IsPage, Where.Text.Contains(queryText));

var results = await client.Content.SearchAsync(query, limit: Limit);
`

I try to search pages and it works great mostly, but  some of the values of  `queryText` parameter causes the ArgumentException "Requested value 'personal' was not found.". It seems that 'personal' value is not a valid name of the some Enum. How can I solve this?

Here is a stacktrace:

   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 243
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 341
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 341
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 432
   at Dapplo.HttpExtensions.JsonSimple.PocoJsonSerializerStrategy.DeserializeObject(Object value, Type type) in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions.JsonSimple\PocoJsonSerializerStrategy.cs:line 341
   at Dapplo.HttpExtensions.ContentConverter.DefaultJsonHttpContentConverter.<ConvertFromHttpContentAsync>d__17.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\ContentConverter\DefaultJsonHttpContentConverter.cs:line 129
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.HttpContentExtensions.<GetAsAsync>d__3.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpContentExtensions.cs:line 109
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.HttpResponseMessageExtensions.<GetAsAsync>d__1`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpResponseMessageExtensions.cs:line 104
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.HttpClientExtensions.<GetAsAsync>d__4`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\HttpClientExtensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.HttpExtensions.UriActionExtensions.<GetAsAsync>d__3`1.MoveNext() in C:\projects\dapplo-httpextensions\src\Dapplo.HttpExtensions\UriActionExtensions.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Dapplo.Confluence.ContentExtensions.<SearchAsync>d__9.MoveNext() in C:\projects\dapplo-confluence\src\Dapplo.Confluence\ContentExtensions.cs:line 294
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ChatBots.Wiki.ConfluenceApi.<GetPagesByTextAsync>d__6.MoveNext() in F:\git\Chatly\ChatBots\Wiki\ConfluenceApi.cs:line 77

**Comment by Lakritzator** [comment]
Sorry for the delay, I didn't have a working computer for 2 weeks.

Do you have some test data, for the query text, which always cause an issue?

P.S.
What version of my library are you using?

**Comment by argnist** [comment]
Dapplo.Confluence version 0.7.6.0

Query text in Russian "Клиент", "веб", "статус" and English "issues" always cause an issue, for example

```
var query = Where.Text.Contains(queryText);
query = Where.And(Where.Type.IsPage, or); // if remove this line there is no error but number of results is less than limit and depends on limit (45 results for 55 limit, 33 results for 40 limit and so on)
var asyncResult = await client?.Content?.SearchAsync(query, limit: Limit); // Exception here
```

**Comment by kudaba** [comment]
Not sure what personal type is but simple solution was just adding:

		/// <summary>
		/// The content is a personal page?
		/// </summary>
		[EnumMember(Value = "personal")] Personal

to src\Dapplo.Confluence\Query\ContentTypes.cs (sorry, I'm not in a state to make a proper pull request)

**Comment by Lakritzator** [comment]
@kudaba thanks for the hint, this should indeed be the solution.

I updated the library, there is a new version 0.7.7 which should fix this issue.
Please test.
